### ISSUE TITLE
Nexus Errors Out

### ISSUE THREAD

**Issue by christianh814** [samueltauil/nexus#2]
Cannot build using this nexus repo

```
Cloning "https://github.com/RedHatWorkshops/kitchensink" ...
	Commit:	731c40ecf92a9bfe408338be5c002d2179149535 (Update pom.xml)
	Author:	VeerMuchandi <veer.muchandi@gmail.com>
	Date:	Tue Nov 22 18:00:24 2016 -0500

Found pom.xml... attempting to build with 'mvn -e -Popenshift -DskipTests -Dcom.redhat.xpaas.repo.redhatga package -Djava.net.preferIPv4Stack=true '
Picked up JAVA_TOOL_OPTIONS: -Duser.home=/home/jboss -Duser.name=jboss
Using Apache Maven 3.0.5 (Red Hat 3.0.5-17)
Maven home: /usr/share/maven
Java version: 1.8.0_111, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.111-2.b15.el7_3.x86_64/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.10.0-514.2.2.el7.x86_64", arch: "amd64", family: "unix"
Picked up JAVA_TOOL_OPTIONS: -Duser.home=/home/jboss -Duser.name=jboss
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
Downloading: http://nexus-workshop.apps.m0.gcloud.rht-labs.com/org/jboss/bom/eap/jboss-javaee-6.0-with-tools/6.4.0.GA/jboss-javaee-6.0-with-tools-6.4.0.GA.pom
Downloading: http://nexus-workshop.apps.m0.gcloud.rht-labs.com/org/jboss/bom/eap/jboss-javaee-6.0-with-hibernate/6.4.0.GA/jboss-javaee-6.0-with-hibernate-6.4.0.GA.pom
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact org.jboss.bom.eap:jboss-javaee-6.0-with-tools:pom:6.4.0.GA in mirror.default (http://nexus-workshop.apps.m0.gcloud.rht-labs.com) @ line 73, column 25
[ERROR] Non-resolvable import POM: Could not find artifact org.jboss.bom.eap:jboss-javaee-6.0-with-hibernate:pom:6.4.0.GA in mirror.default (http://nexus-workshop.apps.m0.gcloud.rht-labs.com) @ line 80, column 25
[ERROR] 'dependencies.dependency.version' for javax.enterprise:cdi-api:jar is missing. @ line 97, column 21
[ERROR] 'dependencies.dependency.version' for org.jboss.spec.javax.annotation:jboss-annotations-api_1.1_spec:jar is missing. @ line 105, column 21
[ERROR] 'dependencies.dependency.version' for org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_1.1_spec:jar is missing. @ line 113, column 21
[ERROR] 'dependencies.dependency.version' for org.hibernate.javax.persistence:hibernate-jpa-2.0-api:jar is missing. @ line 121, column 21
[ERROR] 'dependencies.dependency.version' for org.jboss.spec.javax.ejb:jboss-ejb-api_3.1_spec:jar is missing. @ line 129, column 21
[ERROR] 'dependencies.dependency.version' for org.hibernate:hibernate-validator:jar is missing. @ line 138, column 21
[ERROR] 'dependencies.dependency.version' for org.jboss.spec.javax.faces:jboss-jsf-api_2.1_spec:jar is missing. @ line 152, column 21
[ERROR] 'dependencies.dependency.version' for org.hibernate:hibernate-jpamodelgen:jar is missing. @ line 162, column 21
[ERROR] 'dependencies.dependency.version' for org.hibernate:hibernate-validator-annotation-processor:jar is missing. @ line 170, column 21
[ERROR] 'dependencies.dependency.version' for junit:junit:jar is missing. @ line 177, column 21
[ERROR] 'dependencies.dependency.version' for org.jboss.arquillian.junit:arquillian-junit-container:jar is missing. @ line 186, column 21
[ERROR] 'dependencies.dependency.version' for org.jboss.arquillian.protocol:arquillian-protocol-servlet:jar is missing. @ line 192, column 21

at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:363)
at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:636)
at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven.java:585)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:234)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
[ERROR]
[ERROR]   The project org.jboss.quickstarts.eap:jboss-kitchensink:6.4.0-SNAPSHOT (/home/jboss/source/pom.xml) has 14 errors
[ERROR]     Non-resolvable import POM: Could not find artifact org.jboss.bom.eap:jboss-javaee-6.0-with-tools:pom:6.4.0.GA in mirror.default (http://nexus-workshop.apps.m0.gcloud.rht-labs.com) @ line 73, column 25 -> [Help 2]
org.apache.maven.model.resolution.UnresolvableModelException: Could not find artifact org.jboss.bom.eap:jboss-javaee-6.0-with-tools:pom:6.4.0.GA in mirror.default (http://nexus-workshop.apps.m0.gcloud.rht-labs.com)
at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:159)
at org.apache.maven.model.building.DefaultModelBuilder.importDependencyManagement(DefaultModelBuilder.java:953)
at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:400)
at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:371)
at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:560)
at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:352)
at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:636)
at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven.java:585)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:234)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not find artifact org.jboss.bom.eap:jboss-javaee-6.0-with-tools:pom:6.4.0.GA in mirror.default (http://nexus-workshop.apps.m0.gcloud.rht-labs.com)
at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)
at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:193)
at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:286)
at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:155)
... 20 more
Caused by: org.sonatype.aether.transfer.ArtifactNotFoundException: Could not find artifact org.jboss.bom.eap:jboss-javaee-6.0-with-tools:pom:6.4.0.GA in mirror.default (http://nexus-workshop.apps.m0.gcloud.rht-labs.com)
at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:947)
at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:939)
at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:669)
at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
[ERROR]     Non-resolvable import POM: Could not find artifact org.jboss.bom.eap:jboss-javaee-6.0-with-hibernate:pom:6.4.0.GA in mirror.default (http://nexus-workshop.apps.m0.gcloud.rht-labs.com) @ line 80, column 25 -> [Help 2]
org.apache.maven.model.resolution.UnresolvableModelException: Could not find artifact org.jboss.bom.eap:jboss-javaee-6.0-with-hibernate:pom:6.4.0.GA in mirror.default (http://nexus-workshop.apps.m0.gcloud.rht-labs.com)
at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:159)
at org.apache.maven.model.building.DefaultModelBuilder.importDependencyManagement(DefaultModelBuilder.java:953)
at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:400)
at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:371)
at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:560)
at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:352)
at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:636)
at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven.java:585)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:234)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not find artifact org.jboss.bom.eap:jboss-javaee-6.0-with-hibernate:pom:6.4.0.GA in mirror.default (http://nexus-workshop.apps.m0.gcloud.rht-labs.com)
at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)
at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:193)
at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:286)
at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:155)
... 20 more
Caused by: org.sonatype.aether.transfer.ArtifactNotFoundException: Could not find artifact org.jboss.bom.eap:jboss-javaee-6.0-with-hibernate:pom:6.4.0.GA in mirror.default (http://nexus-workshop.apps.m0.gcloud.rht-labs.com)
at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:947)
at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:939)
at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:669)
at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
[ERROR]     'dependencies.dependency.version' for javax.enterprise:cdi-api:jar is missing. @ line 97, column 21
[ERROR]     'dependencies.dependency.version' for org.jboss.spec.javax.annotation:jboss-annotations-api_1.1_spec:jar is missing. @ line 105, column 21
[ERROR]     'dependencies.dependency.version' for org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_1.1_spec:jar is missing. @ line 113, column 21
[ERROR]     'dependencies.dependency.version' for org.hibernate.javax.persistence:hibernate-jpa-2.0-api:jar is missing. @ line 121, column 21
[ERROR]     'dependencies.dependency.version' for org.jboss.spec.javax.ejb:jboss-ejb-api_3.1_spec:jar is missing. @ line 129, column 21
[ERROR]     'dependencies.dependency.version' for org.hibernate:hibernate-validator:jar is missing. @ line 138, column 21
[ERROR]     'dependencies.dependency.version' for org.jboss.spec.javax.faces:jboss-jsf-api_2.1_spec:jar is missing. @ line 152, column 21
[ERROR]     'dependencies.dependency.version' for org.hibernate:hibernate-jpamodelgen:jar is missing. @ line 162, column 21
[ERROR]     'dependencies.dependency.version' for org.hibernate:hibernate-validator-annotation-processor:jar is missing. @ line 170, column 21
[ERROR]     'dependencies.dependency.version' for junit:junit:jar is missing. @ line 177, column 21
[ERROR]     'dependencies.dependency.version' for org.jboss.arquillian.junit:arquillian-junit-container:jar is missing. @ line 186, column 21
[ERROR]     'dependencies.dependency.version' for org.jboss.arquillian.protocol:arquillian-protocol-servlet:jar is missing. @ line 192, column 21
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
Aborting due to error code 1 from Maven build

error: build error: non-zero (13) exit code from registry.access.redhat.com/jboss-eap-6/eap64-openshift@sha256:ee2a1ba5ad72e9ac2cc8e800a280ea6f60f9b3920f5d0fcde9ad15724eb372f2
```

**Comment by samueltauil** [comment]
you need to add the repositories to the maven-public proxy group on nexus in order to get the build working. To do so, login on nexus instance as admin/admin123 and click in the engine icon on top and then select repositories, find the maven-public and click on it, you will be able to see the redhat repositories added by the provision script, so move them to the right list and save it. Then run the build again.
